### ISSUE TITLE
msqrobsum

### ISSUE THREAD

**Issue by Angrist75** [YanglabWCH/StatsPro#1]
Unfortunately I can not start the software I think for a version incompatibility 
I report the log
thanks for the help
Andrea

if(!require(pacman)) install.packages("pacman")
Loading required package: pacman
Warning message:
package ‘pacman’ was built under R version 4.1.1 
> pacman::p_load(shiny, shinyjs, shinyBS, rlang, htmltools, shinyWidgets, gdata, ggplot2, ggsci, DT, tidyverse, ggExtra, cowplot, readxl, writexl, data.table, Amelia, impute, coin, exactRankTests, genefilter, geneplotter, limma, samr, RankProd, ROTS, MSnbase, DEqMS, plgem, effsize, patchwork, parallelly, listenv, globals, future, future.apply, survcomp, EDASeq, NOISeq, baySeq, NBPSeq, log4r)
> install.packages("https://www.bioconductor.org/packages//2.10/bioc/src/contrib/DESeq_1.8.3.tar.gz", repos = NULL, type = "source")
trying URL 'https://www.bioconductor.org/packages//2.10/bioc/src/contrib/DESeq_1.8.3.tar.gz'
Content type 'application/x-tar' length 1616739 bytes (1.5 MB)
downloaded 1.5 MB

* installing *source* package 'DESeq' ...
** using staged installation
** libs

*** arch - i386
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-41~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c pval.c -o pval.o
pval.c: In function 'add_from_both_sides':
pval.c:26:11: warning: unused variable 'esttotalperlength' [-Wunused-variable]
    double esttotalperlength = total/2;
           ^~~~~~~~~~~~~~~~~
C:/rtools40/mingw32/bin/gcc -shared -s -static-libgcc -o DESeq.dll tmp.def pval.o -LC:/PROGRA~1/R/R-41~1.0/bin/i386 -lR
installing to C:/Program Files/R/R-4.1.0/library/00LOCK-DESeq/00new/DESeq/libs/i386

*** arch - x64
"C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-41~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c pval.c -o pval.o
pval.c: In function 'add_from_both_sides':
pval.c:26:11: warning: unused variable 'esttotalperlength' [-Wunused-variable]
    double esttotalperlength = total/2;
           ^~~~~~~~~~~~~~~~~
C:/rtools40/mingw64/bin/gcc -shared -s -static-libgcc -o DESeq.dll tmp.def pval.o -LC:/PROGRA~1/R/R-41~1.0/bin/x64 -lR
installing to C:/Program Files/R/R-4.1.0/library/00LOCK-DESeq/00new/DESeq/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'DESeq'
    finding HTML links ... done
    CountDataSet-class                      html  
    adjustScvForBias                        html  
    conditions                              html  
REDIRECT:topic	 conditions<-,CountDataSet-method -> conditions.html [ FAIL ]
    counts                                  html  
REDIRECT:topic	 counts<-,CountDataSet,matrix-method -> counts.html [ FAIL ]
    dispTable                               html  
    estimateDispersions                     html  
    estimateSizeFactors                     html  
    estimateSizeFactorsForMatrix            html  
    estimateVarianceFunctions               html  
    fitInfo                                 html  
    fitNbinomGLMs                           html  
    fitNbinomGLMsForMatrix                  html  
    getBaseMeansAndVariances                html  
    getVarianceStabilizedData               html  
    makeExampleCountDataSet                 html  
    nbinomGLMTest                           html  
    nbinomTest                              html  
    nbinomTestForMatrices                   html  
    nbkd.sf                                 html  
    newCountDataSet                         html  
    residualsEcdfPlot                       html  
    scvPlot                                 html  
    sizeFactors                             html  
REDIRECT:topic	 sizeFactors<-,CountDataSet,numeric-method -> sizeFactors.html [ FAIL ]
    varianceFitDiagnostics                  html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (DESeq)
> devtools::install_github("statOmics/MSqRobSum")
Skipping install of 'msqrobsum' from a github remote, the SHA1 (6e55c55c) has not changed since last install.
  Use `force = TRUE` to force installation
> pacman::p_load(metaseqR)
Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.1:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.1/PACKAGES'
Warning messages:
1: package ‘metaseqR’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In p_install(package, character.only = TRUE, ...) : 
3: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘metaseqR’
4: In pacman::p_load(metaseqR) : Failed to install/load:
metaseqR

**Comment by YanglabWCH** [comment]
Hi Andrea,

It looks that you do not install the packages right. For example, metaseqR, you can google this package and find how to install this package or download it and install it locally (https://bioconductor.riken.jp/packages/3.9/bioc/src/contrib/metaseqR_1.24.0.tar.gz).

Please try it again.

Shisheng
