### ISSUE TITLE
Local installation does not work.

### ISSUE THREAD

**Issue by k-p4** [YanglabWCH/StatsPro#2]
Running
`if(!require(pacman)) install.packages("pacman")
pacman::p_load(shiny, shinyjs, shinyBS, rlang, htmltools, shinyWidgets, gdata, ggplot2, ggsci, DT, tidyverse, ggExtra, cowplot, readxl, writexl, data.table, Amelia, impute, coin, exactRankTests, genefilter, geneplotter, limma, samr, RankProd, ROTS, MSnbase, DEqMS, plgem, effsize, patchwork, parallelly, listenv, globals, future, future.apply, survcomp, EDASeq, NOISeq, baySeq, NBPSeq, log4r)
install.packages("https://www.bioconductor.org/packages//2.10/bioc/src/contrib/DESeq_1.8.3.tar.gz", repos = NULL, type = "source")
devtools::install_github("statOmics/MSqRobSum")
pacman::p_load(metaseqR)`

gives the error:
`
1: package metaseqR is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In p_install(package, character.only = TRUE, ...) : 
3: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called metaseqR
4: In pacman::p_load(metaseqR) : Failed to install/load:
metaseqR
`
metaseqR is a depreciated package according to its github page and has been replaced by metaseqR2. It cannot be installed as it is not available.

Additionally, on Ubuntu, when running 
`if(!require(StatsPro)) devtools::install_github("YanglabWCH/StatsPro")
library(StatsPro)
StatsPro_app()`

The error 
`> if(!require(StatsPro)) devtools::install_github("YanglabWCH/StatsPro")
Loading required package: StatsPro
Error in loadNamespace(x) : there is no package called ‘devtools’
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘StatsPro’`

Is displayed even after successful devtools installation. Any insights into this would also be appreciated.
Thank you.

**Comment by Daeveb** [comment]
I also had this problem (R 4.1.1 and 4.0.5) on Win 10 64bit and other issues.  Thank you for your excellent paper and web based portal to the app.
Could you please provide details of which version of R, Bioconductor, and which versions of packages you are using on your web based version please to help local install?


metaseqR installed
Failed with error:  ‘package ‘EDASeq’ could not be loaded’
In addition: Warning message:
package ‘metaseqR’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
Warning message:
In pacman::p_load(metaseqR) : Failed to install/load:
metaseqR

And also when installing DESeq using the command from your instructions:

ERROR: dependency 'locfit' is not available for package 'DESeq'
* removing 'C:/Users/XXXXX/Documents/R/win-library/4.0/DESeq'
Warning message:
In install.packages("https://www.bioconductor.org/packages//2.10/bioc/src/contrib/DESeq_1.8.3.tar.gz",  :
  installation of package ‘C:/Users/XXXXX/AppData/Local/Temp/RtmpWeivkZ/downloaded_packages/DESeq_1.8.3.tar.gz’ had non-zero exit status


Then trying to install locfit manually:

package ‘locfit’ is not available for this version of R

**Comment by Daeveb** [comment]
Update: I have managed to get it working locally I think (and figured out how to install metaseqR).

R 4.0.5, I installed Bioconductor 3.12 (as metaseqR was removed in version 3.13 and above). I updated everything from "source" when prompted to in RStudio, occasionally things would not install and I had to leave RStudio and open RGui as Admin to install them.

I tried to install metaseqR - but errored it needed DESeq installing first which had not installed earlier due to missing a dependency "locfit".  locfit was not available on R 4.0, so I installed from source from https://cran.r-project.org/src/contrib/Archive/locfit/[locfit_1.5-9.4.tar.gz

Running StatsPro_app() now worked, but I received an error that I needed to install a package called "raster".  I did this and ran it again.

I think it is now working as the example dataset was downloaded and then uploaded, and processed and I received the same results in the final "performance" tab in my local R version as the Web Portal version gave.

Now just to figure out how to import DIANN results.

**Comment by wangshisheng** [comment]
Hi all,

Sorry for this late reply. I will check it.


Shisheng

**Comment by YanglabWCH** [comment]
Hi All,

I have checked the installation of StatsPro and updated the steps

```r
if(!require(pacman)) install.packages("pacman")
if(!require(BiocManager)) install.packages('BiocManager')
pacman::p_load(devtools, shiny, shinyjs, shinyBS, rlang, htmltools, shinyWidgets, gdata, gplots, ggplot2, ggsci, DT, tidyverse, ggExtra, cowplot, readxl, writexl, data.table, Amelia, impute, coin, exactRankTests, genefilter, geneplotter, qvalue, limma, samr, RankProd, ROTS, MSnbase, DEqMS, plgem, effsize, patchwork, parallelly, listenv, globals, future, future.apply, survcomp, EDASeq, NOISeq, baySeq, NBPSeq, log4r, raster, corrplot)
install.packages("https://www.bioconductor.org/packages//2.10/bioc/src/contrib/DESeq_1.8.3.tar.gz", repos = NULL, type = "source")
devtools::install_github("statOmics/MSqRobSum")
install.packages("https://www.bioconductor.org/packages/3.9/bioc/src/contrib/metaseqR_1.24.0.tar.gz", repos = NULL, type = "source")
devtools::install_github("YanglabWCH/StatsPro")
```

My R information:
```r
> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
```

Hope it helps and thanks a lot for your feedbacks. Please feel free to contact me.


Bests,
Shisheng
