### ISSUE TITLE
Error:there is no package called ‘writexl’

### ISSUE THREAD

**Issue by Daeveb** [YanglabWCH/StatsPro#3]
Hi, running the web version - with the example data (or any data) this error comes up immediately on the next tab after upload data.

Error: there is no package called ‘writexl’

**Comment by wangshisheng** [comment]
Hi, please refresh your browser and try it again. Thanks a lot for your feedback.

**Comment by Daeveb** [comment]
Many thanks - sorry for the late reply, I was on leave.

**Comment by Daeveb** [comment]
solved
